services:
  - type: web
    name: heart-d
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
